version: "3"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "6500:5432"
    volumes:
      - pgData:/var/lib/postgresql/data
    env_file:
      - ./.env
volumes:
  pgData:
